name: Greeting on variable day

on:
  workflow_dispatch


  

jobs:
  greeting_job:
    runs-on: ubuntu-latest
  
    
    steps:
      - name: "Step 1"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: sandeep
          DAY_OF_WEEK: sunday
          Greeting: Hello
      - name: "Step 2"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
 
