name: ENV Example 
on:
  push:
  
jobs:
  deploy_staging:
   runs-on: ubuntu-latest
   environment: staging
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: print the staging Enviroment message
      run: echo " deploying to the staging with API key = ${{secrets.API_KEY}}"
    
  deploy_production:
   runs-on: ubuntu-latest
   environment: production
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: print the Production Enviroment message
      run: echo " deploying to the Production with API key = ${{secrets.API_KEY}}"
