name: Demo Workflow   # Workflow name

on: 
  pull_request: # Trigger (runs on push)
    types: [closed]
    branches:
     - main
    paths:
     - "application.txt"

jobs:
  build:              # Job name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3   # Step 1: Checkout code
      - run: echo "Hello, GitHub Actions!"  # Step 2: Run command
